server:
  port: ${PAYMENT_SERVICE_PORT}

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

external:
  random-number-api:
    url: ${EXTERNAL_API_URL}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
