name: SonarQube
on:
  push:
    branches:
      - tasks/PAYM-0
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, Test, Analyze and Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Setup Testcontainers
        run: |
          echo "DOCKER_API_VERSION=1.44" >> $GITHUB_ENV
          echo "TESTCONTAINERS_RYUK_DISABLED=true" >> $GITHUB_ENV
          echo "DOCKER_HOST=unix:///var/run/docker.sock" >> $GITHUB_ENV

      - name: Build, test and run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          EXTERNAL_API_URL: https://www.randomnumberapi.com/api/v1.0
          DOCKER_API_VERSION: '1.44'
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=voolk211_shop-PaymentService
      - name: Build Docker image
        run: docker build -t payment-service:${{ github.sha }} .